import * as GC from '@mescius/spread-sheets';

// SpreadJS 라이선스 설정
// localhost에서는 라이센스 없이 실행 (워터마크 표시됨)
// Vercel 배포 환경에서만 라이센스 적용
if (typeof window !== 'undefined' &&
    (window.location.hostname.includes('vercel.app') || window.location.hostname === 'spreadjstest.vercel.app')) {
  GC.Spread.Sheets.LicenseKey = "spreadjstest.vercel.app,E747174387615397#B15NhEFcJtiSqVUV8UTRudEVJZEM5g4MF3Cd4xkW94Gb4okaLlWWN34N9J7dWtkTDJHezpXY9hWczVHTW3kMYhnVOV5SxFHSDBDWFZ5dFFTVnhlUFBzdEFDZTpkcmlHMIFEUPJnZvNVQuVzL0VkT9BTSlZkRwFlb7QDO9MXd6YUQtB5chZEdLR4RyokS6UlRD5UR8hjN7dTVPNjNudkTvp7YsFUWHNlR94Wdhl4YHJUZyQzKsFVV5kmWMZUUY3SSUFjU7Njdsh6d4kGUCFVZ4k7djhzcyRUcNZjW9RVQoBVb7sScjpXNRB5YrRXU8tieI3COzI6KzMVQXxWO0JzdyskMUN7KvJ7RRdEThdVUzADVvAnQBdFT9NjNyh6NM5kTiojITJCLiU4M4YjMCJiOigkIskDN7kzN8cjN0IicfJye#4Xfd5nIIlkSCJiOiMkIsICOx8idgMlSgQWYlJHcTJiOi8kI1tlOiQmcQJCLiQzM5UDOwACOyATM5IDMyIiOiQncDJCLicjMxETNyAjMiojIwhXRiwiIwBXYuwWZjJXZ69CdzVGdzpGZhVmcwNnI0IyctRkIsICsL6OtdyOhVyOl3yOkXyuI0ISYONkIsUWdyRnOiwmdFJCLicTOzUTM6cDOzQzNxcDN7IiOiQWSiwSfdJCdlVGaTRncvBXZSJCLiQnchh6QhRXYEJCLiQXZlh6U4RnbhdkIsISZsJWYUR7b6lGUislOicGbmJCLlNHbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TPRRnQ6sUNBd7Z7NEZat4Zp5USRtEeFZEZylUQkBVdqZFZvBzKUh5UDdTQyknQ64mZmZWaCBXWxR";
  console.log('✅ SpreadJS License applied for Vercel deployment');
} else {
  console.warn('⚠️ Running in trial mode (localhost). Watermark will be displayed.');
  console.warn('Deploy to Vercel to use the full license.');
}

// Designer 라이선스가 필요한 경우 아래 주석을 해제하세요
// import '@mescius/spread-sheets-designer';
// GC.Spread.Sheets.Designer.LicenseKey = "spreadjstest.vercel.app,E267362549483976#B1xpZMhZ5aBZHSBVmYrczUyI7MidFOk34Rvg5NKpHd7MVUspHRVRTYyF6ZLRDZ5NDS7F7bzhnblBVb6QHVvh5UxFlbaRlRXJnNYl7a9Yja6FGdvd5cF5mSElGNzcUWPFHWjJle7RmelVVap3mdydja8VFeW3ie0JGMZh4RZV6Rld5NrUEVlhGUHdUQNZmNDd5ZoBVRBplcHVHUiZFT7hzTNRnc5QHcZJWQvt6a9QUNxg5NGpVSxEFVzcGcxYDTSt6MwhFVEp7avAFdtJTcIB5YXJ6aU3kd9oGb9IzK9h4TUV6apV5K6EFWTlzVXV7Kk3WTMd6VWJld9RXZMtWTYhmdhRzSHFHTv8mYHtEOxgHeSFzbXV4dtVFRvVGb6glVWtyZwsGWSJkI0IyUiwiIERTNDZURzIiOigkIsADN9YDO4EjM0IicfJye#4Xfd5nI9k5MzIiOiMkIsICOx8idg86bkRWQtIXZudWazVGRtMlSkFWZyB7UiojIOJyebpjIkJHUiwiI7QTN5gDMggjMwETNyAjMiojI4J7QiwiI7ITMxUjMwIjI0ICc8VkIsICcwFmLsV6YyVmduQ7clR7cqRWYlJHczJiOiMXbEJCLiA1itTbnsTYlsTZvsD9lsLiOiEmTDJCLlVnc4pjIsZXRiwiI6cTOzgDN9QTNyYzM7YjMiojIklkIs4XXiQXZlh6U4J7bwVmUiwiI4JXYoNUY4FGRiwiI4VWZoNFd49WYHJCLiUGbiFGV43mdpBlIbpjInxmZiwSZzxWYmpjIyNHZisnOiwmbBJye0ICRiwiI34TQxMkVYRHTxgWUJRGWkpEUQZnU5F5avUjU94ETOFjb9hka9ZzUnVEaYRlQ6l6VwhRe";
